#!/bin/bash
chown --guilum betty hello[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[Caum  [D  [D[5~[5~[D[C[C[D[D [D[D[C[C[C [D[D[Dbetty hello[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D  [C[C[C[C[C[C[C[C[C[C[from=guillaume betty hello
